[package]
name = "cg_tracing"
version = "0.1.0"
authors = ["xalanq <xalanq@gmail.com>"]
edition = "2018"

[dependencies]
pbr = "1.0.1"
rand = "0.6.5"
rayon = "1.0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
image = "0.21.0"
pdqselect = "0.1.0"
